name: 'Composite Action Sandbox'
description: 'Get started with Composite actions'
branding:
  icon: 'award'  
  color: 'green'
runs:
  using: "composite"
  steps:
    - run: docker compose -f ${GITHUB_ACTION_PATH}/compose.yaml up -d --wait
      shell: bash
