name: 'Composite Action Sandbox'
description: 'Get started with Composite actions'
branding:
  icon: 'award'  
  color: 'green'
runs:
  using: "composite"
  steps:
    - run: ls -la /
      shell: bash
    - run: docker compose version
      shell: bash
    - run: |
        pwd
        echo $JENKINS_HOME
        if [[ "$JENKINS_HOME" != "/*" ]]; then
          echo "JENKINS_HOME=$(pwd)/${JENKINS_HOME}" >> $GITHUB_ENV
          cat $GITHUB_ENV
        fi
      shell: bash
      env:
        JENKINS_HOME: ./jenkins_home
    - run: |
        mkdir -p $JENKINS_HOME
        sudo chown -R 1000:1000 $JENKINS_HOME
      shell: bash
    - run: docker-compose -f ${GITHUB_ACTION_PATH}/compose.yaml config
      shell: bash
    - run: docker compose -f ${GITHUB_ACTION_PATH}/compose.yaml up
      shell: bash
#     - run: docker compose -f ${GITHUB_ACTION_PATH}/compose.yaml up -d --wait
#       shell: bash
