services:
  jenkins:
    build:
      context: .
    ports:
      - 8081:8080
      - 50001:50000
    volumes:
      - ${JENKINS_HOME}:/var/jenkins_home
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
