name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner: [ ubuntu-22.04, windows-2019 ]
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 10
    defaults:
      run:
        shell: pwsh

    steps:
      - uses: SnowCait/composite-sandbox@main
      - run: serverless --version
#       - uses: actions/checkout@v3
#       - uses: ./
