name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - uses: ./
